spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:port/tablename
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create
      # ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true